export const CAR_MAKES = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Porsche',
  'Ram',
  'Rolls-Royce',
  'Subaru',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
] as const

export const CAR_MODELS: Record<string, string[]> = {
  Acura: ['ILX', 'TLX', 'RLX', 'MDX', 'RDX', 'NSX', 'Integra'],
  'Alfa Romeo': ['Giulia', 'Stelvio', '4C', 'Tonale'],
  Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'RS3', 'RS5', 'RS6', 'RS7', 'R8', 'TT'],
  BMW: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'X1', 'X3', 'X5', 'X6', 'X7', 'Z4', 'i4', 'i7', 'iX', 'M3', 'M4', 'M5', 'M8'],
  Chevrolet: ['Spark', 'Sonic', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Equinox', 'Blazer', 'Traverse', 'Tahoe', 'Suburban', 'Colorado', 'Silverado', 'Bolt EV', 'Bolt EUV'],
  Dodge: ['Challenger', 'Charger', 'Durango', 'Hornet'],
  Ford: ['Fiesta', 'Focus', 'Fusion', 'Mustang', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Bronco', 'Ranger', 'F-150', 'F-250', 'F-350', 'Maverick', 'Mach-E'],
  Honda: ['Fit', 'Civic', 'Accord', 'Insight', 'HR-V', 'CR-V', 'Passport', 'Pilot', 'Ridgeline', 'Odyssey', 'Prologue'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Azera', 'Veloster', 'Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Ioniq 5', 'Ioniq 6'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator', 'Wagoneer'],
  Kia: ['Rio', 'Forte', 'K5', 'Stinger', 'Soul', 'Seltos', 'Sportage', 'Sorento', 'Telluride', 'Carnival', 'EV6', 'EV9'],
  Lexus: ['IS', 'ES', 'GS', 'LS', 'RC', 'LC', 'UX', 'NX', 'RX', 'GX', 'LX', 'RZ'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'AMG GT', 'EQE', 'EQS'],
  Nissan: ['Versa', 'Sentra', 'Altima', 'Maxima', 'Z', 'Kicks', 'Rogue Sport', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'Leaf', 'Ariya'],
  Porsche: ['718 Boxster', '718 Cayman', '911', 'Panamera', 'Cayenne', 'Macan', 'Taycan'],
  Subaru: ['Impreza', 'Legacy', 'WRX', 'BRZ', 'Crosstrek', 'Forester', 'Outback', 'Ascent', 'Solterra'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  Toyota: ['Yaris', 'Corolla', 'Camry', 'Avalon', 'GR86', 'Supra', 'C-HR', 'Corolla Cross', 'RAV4', 'Venza', 'Highlander', '4Runner', 'Sequoia', 'Land Cruiser', 'Tacoma', 'Tundra', 'Prius', 'bZ4X'],
  Volkswagen: ['Jetta', 'Passat', 'Arteon', 'Golf', 'GTI', 'Golf R', 'Taos', 'Tiguan', 'Atlas', 'Atlas Cross Sport', 'ID.4', 'ID.Buzz'],
  Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'EX30', 'EX90'],
}

export const CAR_CONDITIONS = [
  { value: 'NEW', label: 'New' },
  { value: 'LIKE_NEW', label: 'Like New' },
  { value: 'EXCELLENT', label: 'Excellent' },
  { value: 'GOOD', label: 'Good' },
  { value: 'FAIR', label: 'Fair' },
  { value: 'POOR', label: 'Poor' },
] as const

export const CAR_FEATURES = [
  'Air Conditioning',
  'Heated Seats',
  'Leather Seats',
  'Sunroof',
  'Navigation System',
  'Backup Camera',
  'Blind Spot Monitor',
  'Lane Departure Warning',
  'Adaptive Cruise Control',
  'Apple CarPlay',
  'Android Auto',
  'Bluetooth',
  'USB Ports',
  'Wireless Charging',
  'Premium Sound System',
  'Keyless Entry',
  'Push Button Start',
  'Remote Start',
  'Power Windows',
  'Power Locks',
  'Power Mirrors',
  'Power Seats',
  'Memory Seats',
  'Heated Steering Wheel',
  'Parking Sensors',
  '360 Camera',
  'Heads-Up Display',
  'Third Row Seating',
  'Roof Rack',
  'Tow Package',
  'All-Wheel Drive',
  'Four-Wheel Drive',
  'Turbo',
  'Hybrid',
  'Electric',
  'Manual Transmission',
  'Automatic Transmission',
  'Sport Mode',
  'Eco Mode',
  'Performance Package',
  'Luxury Package',
  'Technology Package',
] as const

export const YEAR_MIN = 1990
export const YEAR_MAX = new Date().getFullYear() + 1
export const PRICE_MIN = 0
export const PRICE_MAX = 500000
export const MILEAGE_MIN = 0
export const MILEAGE_MAX = 300000

export const DEFAULT_FILTERS = {
  yearMin: YEAR_MIN,
  yearMax: YEAR_MAX,
  priceMin: PRICE_MIN,
  priceMax: PRICE_MAX,
  mileageMin: MILEAGE_MIN,
  mileageMax: MILEAGE_MAX,
  makes: [] as string[],
  models: [] as string[],
  conditions: [] as string[],
  features: [] as string[],
  location: '',
  distance: 100,
}

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest First' },
  { value: 'oldest', label: 'Oldest First' },
  { value: 'price_low', label: 'Price: Low to High' },
  { value: 'price_high', label: 'Price: High to Low' },
  { value: 'mileage_low', label: 'Mileage: Low to High' },
  { value: 'mileage_high', label: 'Mileage: High to Low' },
  { value: 'year_new', label: 'Year: Newest' },
  { value: 'year_old', label: 'Year: Oldest' },
] as const
